export enum Types{
  FETCH_START_PROV = "FETCH_START_PROV",
  FETCH_SUCCESS_PROV = "FETCH_SUCCESS_PROV",
  FETCH_ERROR_PROV = "FETCH_ERROR_PROV",
  FETCH_START_TOTAL = "FETCH_START_TOTAL",
  FETCH_SUCCESS_TOTAL = "FETCH_SUCCESS_TOTAL",
  FETCH_ERROR_TOTAL = "FETCH_START_TOTAL"
}
