export enum Types{
  FETCH_START = "FETCH_START",
  FETCH_SUCCESS = "FETCH_SUCCESS",
  FETCH_ERROR = "FETCH_ERROR",
  FETCH_START_D = "FETCH_START_D",
  FETCH_SUCCESS_D = "FETCH_SUCCESS_D",
  FETCH_ERROR_D = "FETCH_ERROR_D"
}
